// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHutUFjzGlBrDHRaY63auVO0Aq8F9z6zw',
    appId: '1:844610913923:web:8eaed464e273813f84bdb6',
    messagingSenderId: '844610913923',
    projectId: 'library-project-1651e',
    authDomain: 'library-project-1651e.firebaseapp.com',
    storageBucket: 'library-project-1651e.appspot.com',
    measurementId: 'G-653BM3R8Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU7b9czV1NfntRB968gyWLm2FJ9lxRza8',
    appId: '1:844610913923:android:e975040c7dc65ce484bdb6',
    messagingSenderId: '844610913923',
    projectId: 'library-project-1651e',
    storageBucket: 'library-project-1651e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGYB55Mg4l8qwJUa_FuF4hVhiVGG99w_E',
    appId: '1:844610913923:ios:bea4325c5784c3ae84bdb6',
    messagingSenderId: '844610913923',
    projectId: 'library-project-1651e',
    storageBucket: 'library-project-1651e.appspot.com',
    iosBundleId: 'com.example.libraryProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGYB55Mg4l8qwJUa_FuF4hVhiVGG99w_E',
    appId: '1:844610913923:ios:bea4325c5784c3ae84bdb6',
    messagingSenderId: '844610913923',
    projectId: 'library-project-1651e',
    storageBucket: 'library-project-1651e.appspot.com',
    iosBundleId: 'com.example.libraryProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHutUFjzGlBrDHRaY63auVO0Aq8F9z6zw',
    appId: '1:844610913923:web:9cbe19cf3a49694a84bdb6',
    messagingSenderId: '844610913923',
    projectId: 'library-project-1651e',
    authDomain: 'library-project-1651e.firebaseapp.com',
    storageBucket: 'library-project-1651e.appspot.com',
    measurementId: 'G-EKLQ1E2VPZ',
  );
}
