// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSMSxcmDn2xBBFOuOEjZlH85HZKEYTzgM',
    appId: '1:126778279775:web:cfa7422e7e7b56c79818ea',
    messagingSenderId: '126778279775',
    projectId: 'project1account',
    authDomain: 'project1account.firebaseapp.com',
    storageBucket: 'project1account.firebasestorage.app',
    measurementId: 'G-0HDBLQDW2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7r6c8Eur9WbfnxqqYhvAGeaXK865YxFo',
    appId: '1:126778279775:android:f7cd738623ad6f469818ea',
    messagingSenderId: '126778279775',
    projectId: 'project1account',
    storageBucket: 'project1account.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGohhbIOv2LIpPZG-hpJHyuLDrm5Xw29Y',
    appId: '1:126778279775:ios:a17c16251ef326bc9818ea',
    messagingSenderId: '126778279775',
    projectId: 'project1account',
    storageBucket: 'project1account.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGohhbIOv2LIpPZG-hpJHyuLDrm5Xw29Y',
    appId: '1:126778279775:ios:a17c16251ef326bc9818ea',
    messagingSenderId: '126778279775',
    projectId: 'project1account',
    storageBucket: 'project1account.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSMSxcmDn2xBBFOuOEjZlH85HZKEYTzgM',
    appId: '1:126778279775:web:3ff9bb4184ef72da9818ea',
    messagingSenderId: '126778279775',
    projectId: 'project1account',
    authDomain: 'project1account.firebaseapp.com',
    storageBucket: 'project1account.firebasestorage.app',
    measurementId: 'G-8TK63F7WXL',
  );
}
